#!/usr/bin/env python3

"""
PDF Size Adjuster

This application provides a graphical user interface (GUI) for adjusting the page size of PDF files using the cpdf tool.
Linux, macOS, and Windows platforms are supported (64-bit only).

Most code generated by ChatGPT 4.
"""

import tkinter as tk
from tkinter import filedialog
import subprocess
import sys
import urllib.request
import os
import platform
import re
import threading
from datetime import datetime

def download_cpdf():
    if sys.platform.startswith('linux'):
        platform_name = 'Linux-Intel-64bit'
        binary_name = 'cpdf'
    elif sys.platform == 'darwin':
        platform_name = 'OSX-Intel' if platform.processor() == 'i386' else 'OSX-ARM'
        binary_name = 'cpdf'
    elif sys.platform == 'win32':
        platform_name = 'Windows64bit'
        binary_name = 'cpdf.exe'
    else:
        raise Exception("Unsupported platform")

    save_path = os.path.join(os.getcwd(), binary_name)
    if os.path.exists(save_path):
        return save_path

    download_url = f"https://github.com/coherentgraphics/cpdf-binaries/raw/master/{platform_name}/{binary_name}"

    update_message_box(f"Downloading CPDF for {platform_name}...")
    urllib.request.urlretrieve(download_url, save_path)
    update_message_box(f"CPDF downloaded to script directory.")

    if platform_name != 'Windows64bit':
        os.chmod(save_path, 0o755)

    return save_path

def select_file():
    filepath = filedialog.askopenfilename(filetypes=(("PDF files", "*.pdf"),))
    if filepath:
        file_path_var.set(filepath)

def run_cpdf_command_thread():
    filepath = file_path_var.get()
    pagesize = page_size_var.get()
    if filepath and pagesize:
        try:
            outfilepattern = re.compile(r'\.pdf$', re.IGNORECASE)
            if outfilepattern.search(filepath):
                outputpath = outfilepattern.sub("-output.pdf", filepath)
            else:
                raise Exception("The file path does not end with '.pdf'")

            command = [download_cpdf(), '-scale-to-fit', pagesize, filepath, "-o", outputpath]
            subprocess.run(command, check=True, stderr=subprocess.PIPE, text=True)
            update_message_box("Success: CPDF command executed successfully!")
        except subprocess.CalledProcessError as e:
            lasterrline = e.stderr.strip().split("\n")[-1] if e.stderr else "Unknown error."
            update_message_box(f"CPDF error: {lasterrline}")
        except Exception as e:
            update_message_box(f"Error: {str(e)}")
    else:
        update_message_box("Error: File or page size not given.")

def run_cpdf_command():
    threading.Thread(target=run_cpdf_command_thread).start()

root = tk.Tk()
root.title("PDF Size Adjuster")
root.configure(padx=10, pady=10)

#root.grid_columnconfigure(0, weight=1)
root.grid_rowconfigure(0, weight=1)
root.grid_rowconfigure(4, weight=1)

file_path_var = tk.StringVar()
page_size_var = tk.StringVar()
page_size_var.set("a4portrait")

tk.Label(root, text="PDF File:").grid(row=0, column=0, sticky='w')
pdf_entry = tk.Entry(root, textvariable=file_path_var, state='disabled')
pdf_entry.grid(row=0, column=1, sticky='ew', padx=(10, 10))
tk.Button(root, text="Select", command=select_file).grid(row=0, column=2, sticky='ew')

tk.Label(root, text="Page Size:").grid(row=1, column=0, sticky='w', pady=(10, 0))
page_size_entry = tk.Entry(root, textvariable=page_size_var)
page_size_entry.grid(row=1, column=1, columnspan=2, sticky='ew', padx=(10, 0), pady=(10, 0))

root.columnconfigure(1, weight=1)

tk.Button(root, text="Run", command=run_cpdf_command).grid(row=2, column=0, columnspan=3, sticky='ew', pady=(10, 0))

message_box = tk.Text(root, height=4, state='disabled')
message_box.grid(row=3, column=0, columnspan=3, sticky='ew', pady=(10, 0))

def update_message_box(message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted_message = f"[{timestamp}] {message}"
    current_text = message_box.get(1.0, tk.END)
    if current_text != "\n":
        formatted_message = "\n" + formatted_message

    message_box.config(state='normal')
    message_box.insert(tk.END, formatted_message)
    message_box.see(tk.END)
    message_box.config(state='disabled')

root.mainloop()
